ALTER TABLE cadastre.property_rights DROP CONSTRAINT right_type;
-- ASTRA STATEMENT
ALTER TABLE cadastre.property_rights ADD CONSTRAINT right_type CHECK (right_type IN ('RECORDED_OWNERSHIP','SHARED_USE','ACCESS','EASEMENT','RESTRICTION'));
-- ASTRA STATEMENT

CREATE TABLE cadastre.property_annotations (
	sequence BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	object_id UUID NOT NULL, 
	display_label VARCHAR(160) NOT NULL, 
	address VARCHAR(500), 
	land_use VARCHAR(100), 
	evidence_id UUID NOT NULL, 
	reason TEXT NOT NULL, 
	actor_id UUID NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (sequence), 
	FOREIGN KEY(object_id) REFERENCES cadastre.spatial_objects (id), 
	FOREIGN KEY(evidence_id) REFERENCES cadastre.evidence (id), 
	FOREIGN KEY(actor_id) REFERENCES cadastre.app_users (id)
)

;
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_property_annotations_actor_id ON cadastre.property_annotations (actor_id);
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_property_annotations_object_id ON cadastre.property_annotations (object_id);
-- ASTRA STATEMENT

CREATE TABLE cadastre.right_scopes (
	right_id UUID NOT NULL, 
	related_object_id UUID NOT NULL, 
	reason TEXT NOT NULL, 
	actor_id UUID NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (right_id, related_object_id), 
	FOREIGN KEY(right_id) REFERENCES cadastre.property_rights (id), 
	FOREIGN KEY(related_object_id) REFERENCES cadastre.spatial_objects (id), 
	FOREIGN KEY(actor_id) REFERENCES cadastre.app_users (id)
)

;
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_right_scopes_actor_id ON cadastre.right_scopes (actor_id);
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_right_scopes_related_object_id ON cadastre.right_scopes (related_object_id);
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_right_scopes_right_id ON cadastre.right_scopes (right_id);
-- ASTRA STATEMENT

CREATE TABLE cadastre.workflow_events (
	sequence BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	object_id UUID NOT NULL, 
	geometry_id UUID NOT NULL, 
	before_state VARCHAR(30) NOT NULL, 
	after_state VARCHAR(30) NOT NULL, 
	reason TEXT NOT NULL, 
	actor_id UUID NOT NULL, 
	validation_job_id UUID, 
	review_decision_id UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT workflow_state CHECK (after_state IN ('DRAFT','VALIDATION','VALIDATED','REVIEW','ACCEPTED','CORRECTION_REQUIRED')), 
	UNIQUE (sequence), 
	FOREIGN KEY(object_id) REFERENCES cadastre.spatial_objects (id), 
	FOREIGN KEY(geometry_id) REFERENCES cadastre.geometry_versions (id), 
	FOREIGN KEY(actor_id) REFERENCES cadastre.app_users (id), 
	FOREIGN KEY(validation_job_id) REFERENCES cadastre.processing_jobs (id), 
	FOREIGN KEY(review_decision_id) REFERENCES cadastre.review_decisions (id)
)

;
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_workflow_events_actor_id ON cadastre.workflow_events (actor_id);
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_workflow_events_geometry_id ON cadastre.workflow_events (geometry_id);
-- ASTRA STATEMENT
CREATE INDEX ix_cadastre_workflow_events_object_id ON cadastre.workflow_events (object_id);
-- ASTRA STATEMENT
ALTER TABLE cadastre.property_annotations ENABLE ROW LEVEL SECURITY;
-- ASTRA STATEMENT
CREATE TRIGGER immutable_property_annotations BEFORE UPDATE OR DELETE ON cadastre.property_annotations FOR EACH ROW EXECUTE FUNCTION cadastre.reject_mutation();
-- ASTRA STATEMENT
ALTER TABLE cadastre.right_scopes ENABLE ROW LEVEL SECURITY;
-- ASTRA STATEMENT
CREATE TRIGGER immutable_right_scopes BEFORE UPDATE OR DELETE ON cadastre.right_scopes FOR EACH ROW EXECUTE FUNCTION cadastre.reject_mutation();
-- ASTRA STATEMENT
ALTER TABLE cadastre.workflow_events ENABLE ROW LEVEL SECURITY;
-- ASTRA STATEMENT
CREATE TRIGGER immutable_workflow_events BEFORE UPDATE OR DELETE ON cadastre.workflow_events FOR EACH ROW EXECUTE FUNCTION cadastre.reject_mutation();
-- ASTRA STATEMENT

DO $$ DECLARE t text; BEGIN
IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='astra_app') THEN
 FOREACH t IN ARRAY ARRAY['workflow_events','right_scopes','property_annotations'] LOOP
  EXECUTE format('CREATE POLICY backend_access ON cadastre.%I TO astra_app USING (true) WITH CHECK (true)',t);
  EXECUTE format('GRANT SELECT,INSERT ON cadastre.%I TO astra_app',t);
 END LOOP;
 GRANT USAGE,SELECT ON SEQUENCE cadastre.workflow_events_sequence_seq,cadastre.property_annotations_sequence_seq TO astra_app;
 GRANT UPDATE(role,active) ON cadastre.app_users TO astra_app;
END IF;
END $$;
